
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cake]

		[types.cake.blue_skies]
			comet_berry_pie = true

		[types.cake.mynethersdelight]
			magma_cake = true

	[types.wood_type]

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.deeperdarker]
			bloom = true
			echo = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.blue_skies]
			crystallized = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.wood_type.nethers_exoticism]
			jabuticaba = true
			ramboutan = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.tconstruct]
			greenheart = true
			skyroot = true
			bloodshroom = true
			enderbark = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.biomemakeover]
			blighted_balsa = true
			willow = true
			swamp_cypress = true
			ancient_oak = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.gardens_of_the_dead]
			soulblight = true
			whistlecane = true

	[types.leaves_type]

		[types.leaves_type.blue_skies]
			crystallized = true
			crescent_fruit = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.nethers_exoticism]
			jaboticaba = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.tconstruct]
			earth_slime = true
			sky_slime = true
			ender_slime = true

		[types.leaves_type.croptopia]
			cinnamon = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.biomemakeover]
			blighted_balsa = true
			willow = true
			swamp_cypress = true
			ancient_oak = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true
			golden_apple_acacia = true
			golden_apple_birch = true
			golden_apple_dark_oak = true
			golden_apple_jungle = true
			golden_apple_oak = true
			golden_apple_spruce = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			dining_bench = true
			drawer = true
			side_table = true
			couch = true
			table = true
			chair = true
			shelf = true
			cupboard = true
			bench = true
			pillar_trim = true
			nightstand = true

		[entries.wood_type.twilightforest]
			banister = true
			hollow_log_climbable = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

		[entries.wood_type.decorative_blocks]
			seat = true
			palisade = true
			beam = true
			support = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.twigs]
			table = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.mighty_mail]
			mail_box = true

		[entries.wood_type.infinitybuttons]
			large_button = true
			plank_secret_button = true

		[entries.wood_type.villagersplus]
			horticulturist_table = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.another_furniture]
			flower_box = true
			shutter = true
			drawer = true
			shelf = true
			bench = true
			table = true
			chair = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.hearth_and_home]
			lattice = true
			sanded_wood = true
			parquet = true
			vertical_trim = true
			trim = true

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			tiled_door = true
			classic_trapdoor = true
			circle_glass = true
			center_cut_log = true
			pegged_planks = true
			torch = true
			secret_door = true
			smooth_planks = true
			screen_door = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			crossed_planks = true
			beach_door = true
			fine_vertical_planks = true
			cross_laced_planks = true
			diamond_bordered_glass = true
			railed_planks = true
			planks_mosaic = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			firewood_log = true
			circle_glass_pane = true
			versailles_planks = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			planked_log = true
			mixed_log = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			woven_glass = true
			detailed_planks = true
			woven_trapdoor = true
			cobweb_trapdoor = true
			gated_door = true
			supported_door = true
			barred_trapdoor = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			airy_trapdoor = true
			line_bared_glass = true
			slanted_planks = true
			edge_cut_log = true
			barred_door = true
			suspicious_trapdoor = true
			herringbone_planks = true
			pressed_door = true
			planks_panel = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			solid_trapdoor = true
			tiled_planks = true
			boarded_door = true
			dual_paneled_door = true
			square_glass_pane = true
			meshed_trapdoor = true
			overgrown_log = true
			thin_planks = true
			fancy_trapdoor = true
			paper_door = true
			warted_trapdoor = true
			basket_woven_planks = true
			enclosed_planks = true
			flowering_log = true
			double_herringbone_planks = true
			crated_planks = true
			horizontal_lined_glass = true
			reinforced_log = true
			natural_planks = true
			classic_windowed_trapdoor = true
			brick_bond_planks = true
			wickered_planks = true
			bordered_glass_pane = true
			sliding_door = true
			heavy_trapdoor = true
			bordered_glass = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			shack_door = true
			bundled_log = true
			polished_planks = true
			ornate_bared_glass_pane = true
			diagonal_planks = true
			wall_torch = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			glass_door = true
			fortified_door = true
			paneled_door = true
			leafy_trapdoor = true
			snowflake_glass = true
			heavy_door = true
			pointless_trapdoor = true
			stacked_planks = true
			planks_shavings = true
			twisted_trapdoor = true
			diamond_planks = true
			woven_glass_pane = true
			windowed_trapdoor = true
			tile_windowed_door = true
			damaged_log = true
			golden_barred_trapdoor = true
			nailed_log = true

